### ISSUE TITLE
ignition-gazebo3 build

### ISSUE THREAD

**Issue by Tobias-Fischer** [conda-forge/libignition-gazebo-feedstock#1]
One of the ROS packages (not sure which one) needs ignition-gazebo3 - do you think it's worth building/maintaining a separate branch for that?

**Comment by traversaro** [comment]
In theory it could make sense, given that Ignition Citadel (of which Ignition Gazebo 3 is part) will be maintained till December 2024: https://ignitionrobotics.org/docs/citadel/install#citadel-libraries . However, we also need to provide older version of several other ignition libraries (gui3, rendering3, physics2, sensor3). We can eventually try and check if there are no particular blockers.

**Comment by traversaro** [comment]
> (not sure which one)

I guess it could be https://github.com/ignitionrobotics/ros_ign .

**Comment by Tobias-Fischer** [comment]
Yes, it is only used by ros_ign (see https://index.ros.org/d/ignition-gazebo3/); but as you said ros_ign also supports ignition-gazebo4. So we're all good and should be able to build ros_ign with ignition-gazebo4. Closing here, as building all the dependencies would be quite cumbersome with very little benefit.

Thanks @traversaro!
