### ISSUE TITLE
Fix autotick bot

### ISSUE THREAD

**Issue by traversaro** [conda-forge/libignition-gazebo-feedstock#24]
We still do not get autotick prs for new releases after https://github.com/conda-forge/libignition-gazebo-feedstock/pull/21 .

**Comment by traversaro** [comment]
The relevant line from the autotick bot is (from https://pipelines.actions.githubusercontent.com/dhJXNay2yTbK6bDP34npFl1R3JaUITV6UeZcyVQg965BJrFPdw/_apis/pipelines/1/runs/136928/signedlogcontent/3?urlExpires=2021-10-03T12%3A43%3A48.8263211Z&urlSigningMethod=HMACV1&urlSignature=OR4xrzSrW3zKdX7mOcwMW8NzmuGVK%2BNqKyW%2FcTxtYmk%3D ):
~~~
2021-10-03T11:56:50.4318034Z 2021-10-03 11:56:50,430 INFO     conda_forge_tick.update_upstream_versions || itr  7274 - eta   657s: libignition-gazebo - 5.1.0 - False
~~~

**Comment by traversaro** [comment]
Also in https://github.com/regro/cf-graph-countyfair/blob/master/versions/libignition-gazebo.json the new version is listed as `false` (permalink: https://github.com/regro/cf-graph-countyfair/blob/28b5ce0e61ce26b17f99b93edefb620802499ecc/versions/libignition-gazebo.json) while for working packages it is a version like `6_6.0.0`, see https://github.com/regro/cf-graph-countyfair/blob/28b5ce0e61ce26b17f99b93edefb620802499ecc/versions/libignition-sensors.json .

**Comment by traversaro** [comment]
If someone wants to tackle this, probably something in the logic of the bot needs to be fixed, and the links provided in https://github.com/conda-forge/libignition-msgs1-feedstock/issues/53 and https://github.com/regro/cf-scripts/pull/1421 are the best place were to start.

**Comment by Tobias-Fischer** [comment]
I think this is resolved @traversaro?

**Comment by traversaro** [comment]
Unfortunatly not, we are at 6.1 and the official releases are 6.9 .

**Comment by traversaro** [comment]
The autotick seems not to be working also on https://github.com/conda-forge/libignition-common-feedstock .

**Comment by Tobias-Fischer** [comment]
I think this has been resolved, right @traversaro?

**Comment by traversaro** [comment]
Yes, at least we know why it is not working. But it is working in the latest version of gz libraries.
