### ISSUE TITLE
ign-gazebo defaults to ogre2 rendering engine, that is not available

### ISSUE THREAD

**Issue by traversaro** [conda-forge/libignition-gazebo-feedstock#27]
Launching `ign gazebo` on a platform where this is supported (as 6.0.0_h18f0bbf_1 only Linux) results in:
~~~
[GUI] [Err] [RenderEngineManager.cc:461] Failed to load plugin [ogre2] : couldn't find shared library.
[GUI] [Err] [MinimalScene.cc:514] Engine [ogre2] is not supported
[GUI] [Err] [MinimalScene.cc:653] Unable to initialize renderer
[GUI] [Err] [RenderEngineManager.cc:461] Failed to load plugin [ogre2] : couldn't find shared library.
[GUI] [Err] [MinimalScene.cc:514] Engine [ogre2] is not supported
[GUI] [Err] [MinimalScene.cc:653] Unable to initialize renderer
~~~

This is because ign gazebo defaults to ogre2, that is not packaged at the moment in conda-forge .  To launch it, it is necessary to explicitly launch it with render engine ogre, via the `--render-engine ogre` option:
~~~
ign gazebo --render-engine ogre
~~~

It would be great to either package ogre2, or to patch ignition gazebo to use ogre as default render engine if ogre2 is not available.

**Comment by diegoferigo** [comment]
Another option, especially for those that are not using the command line to start Ignition Gazebo, is editing `~/.ignition/gazebo/6/gui.config` and change `//plugin[@filename=MinimalScene]/engine` from `ogre2` to `ogre`. Probably finding and patching this file could fix at least the new installations, since this file is copied into the user's home the first time Gazebo is launched.

**Comment by traversaro** [comment]
As it is clear from https://github.com/RoboStack/ros-galactic/issues/104, it is not possible to install ogre 1.10 with ROS2, while we have problems with ogre 1.12 tracked in https://github.com/conda-forge/libignition-gazebo-feedstock/issues/6 . At this point, I think the only proper solution is to package ogre-next (what used to be called ogre2 and is still called ogre2 in Gazebo [that used to be called Ignition]). I was kind of waiting for https://github.com/OGRECave/ogre-next/issues/259 to be fixed before so that we could install in the same environment ogre and ogre-next (otherwise we can't have Ignition Gazebo and RViz), but I guess there is no expected release date for that. Probably we could just package the latest ogre-next with a custom patch to fix https://github.com/OGRECave/ogre-next/issues/259, that in the end is what OSRF is doing in their deb packages.

**Comment by traversaro** [comment]
I tried to package ogre-next, but I got stuck as described in https://github.com/conda-forge/staged-recipes/pull/19384#issuecomment-1165733475 .

**Comment by traversaro** [comment]
> I tried to package ogre-next, but I got stuck as described in [conda-forge/staged-recipes#19384 (comment)](https://github.com/conda-forge/staged-recipes/pull/19384#issuecomment-1165733475) .

I then got unstack as described in later comments.

**Comment by traversaro** [comment]
After:
* https://github.com/conda-forge/staged-recipes/pull/19384
* https://github.com/conda-forge/libignition-rendering4-feedstock/pull/45

This problem is solved, at least for Ignition Gazebo 6 on Linux : 

![rosignhumble](https://user-images.githubusercontent.com/1857049/176627889-08c084c7-31c7-4fb1-aba5-c41ba5cde3a2.png)

On WSLg this does not work, but for reason indipendent from the conda packaging that also affect apt packages (llvmpipe has a antialiasing problem, see [gazebosim/gz-sim#1116](https://github.com/gazebosim/gz-sim/issues/1116), while d3d12 does not support the required GL_ARB_copy_image opengl extension).
